package engine_test

import (
	_ "embed"
	"encoding/json"
	"github.com/hcy0317/better-genshin-impact/tools/gcsimbridge/internal/engine"
	"github.com/hcy0317/better-genshin-impact/tools/gcsimbridge/internal/nativeflow"
	"strings"
	"testing"
)

// Generated by the public Java importer from the unmodified 00-水 fixture.
//
//go:embed testdata/native-water.json
var nativeWater []byte

func TestInterruptedStandardChargeNeverReturnsTruncatedQualifiedDamage(t *testing.T) {
	p := &nativeflow.Program{SchemaVersion: "native-flow-v1", Source: "segment(喷射宏,define,atomic,timeout=0.02)",
		Root: []nativeflow.Node{{ID: "call", Kind: "call", Args: []string{"喷射宏"}, Options: map[string]string{"required": "true"}}},
		Blocks: map[string]nativeflow.Block{"喷射宏": {Macro: "neuvillette_charge_v1", Declaration: nativeflow.Node{ID: "macro", Kind: "segment", Options: map[string]string{"atomic": "true", "timeout": "0.02", "record": "宏完成"}}, Nodes: []nativeflow.Node{
			{ID: "down", Kind: "keydown", Character: "neuvillette", Args: []string{"VK_LBUTTON"}, Options: map[string]string{"required": "true"}},
			{ID: "wait", Kind: "wait", Character: "neuvillette", Seconds: 3.52},
			{ID: "up", Kind: "keyup", Character: "neuvillette", Args: []string{"VK_LBUTTON"}},
		}}}}
	report, err := engine.Evaluate(engine.Request{SchemaVersion: "1", EngineRevision: engine.Revision, Seeds: []int64{17}, NativeFlow: p,
		Config: `options duration=10;target lvl=90 resist=0.1;neuvillette char lvl=90/90 cons=0 talent=6,6,6;neuvillette add weapon="prototypeamber" refine=1 lvl=90/90;active neuvillette;`})
	if err == nil || !strings.Contains(err.Error(), "native_flow_indeterminate") {
		t.Fatalf("interruption was not explicit: %v", err)
	}
	if report.MeanDPS != 0 || len(report.Samples) != 0 || report.Validation.State == "passed" {
		t.Fatal("interrupted sample was upgraded into qualified damage")
	}
	for _, trace := range report.NativeFlowTraces {
		for _, e := range trace.Events {
			if e.Kind == "record" && e.Detail == "宏完成" {
				t.Fatal("interrupted macro forged its completion record")
			}
		}
	}
}

func TestFailedOpeningRecoveryDoesNotSatisfyOnceOrCreateItsCompletionRecord(t *testing.T) {
	p := &nativeflow.Program{SchemaVersion: "native-flow-v1", Source: "call(开场,once=battle,required)", Loop: true,
		Root: []nativeflow.Node{{ID: "call", Kind: "call", Args: []string{"开场"}, Options: map[string]string{"once": "battle", "required": "true"}}},
		Blocks: map[string]nativeflow.Block{
			"开场": {Declaration: nativeflow.Node{ID: "opening", Kind: "segment", Options: map[string]string{"record": "开场完成", "onfail": "保底"}}, Nodes: []nativeflow.Node{{ID: "q", Kind: "burst", Character: "kaeya", Options: map[string]string{"required": "true", "timeout": "0.2"}}}},
			"保底": {Declaration: nativeflow.Node{ID: "fallback", Kind: "segment"}, Nodes: []nativeflow.Node{{ID: "e", Kind: "skill", Character: "kaeya"}}},
		}}
	report, err := engine.Evaluate(engine.Request{SchemaVersion: "1", EngineRevision: engine.Revision, Seeds: []int64{17}, NativeFlow: p,
		Config: `options duration=3;target lvl=90 resist=0.1;kaeya char lvl=90/90 cons=0 talent=6,6,6 +params=[start_energy=0];kaeya add weapon="dullblade" refine=1 lvl=90/90;active kaeya;`})
	if err != nil {
		t.Fatal(err)
	}
	openings := 0
	recovered := false
	for _, e := range report.NativeFlowTraces[0].Events {
		if e.Kind == "call" && e.Detail == "开场" {
			openings++
		}
		if e.Kind == "action" && e.Node == "e" {
			recovered = true
		}
		if e.Kind == "record" && e.Detail == "开场完成" || e.Kind == "satisfied" && e.Node == "call" {
			t.Fatalf("recovery forged opening success: %+v", e)
		}
	}
	if openings < 2 || !recovered {
		t.Fatalf("opening did not retry after recovery: %+v", report.NativeFlowTraces)
	}
}

func TestNativeFlowRejectsMixedExecutableGcsimInsteadOfIgnoringIt(t *testing.T) {
	p := &nativeflow.Program{SchemaVersion: "native-flow-v1", Source: "凯亚 e", Root: []nativeflow.Node{{ID: "e", Kind: "skill", Character: "kaeya"}}}
	_, err := engine.Evaluate(engine.Request{SchemaVersion: "1", EngineRevision: engine.Revision, Seeds: []int64{17}, NativeFlow: p,
		Config: `options duration=3;target lvl=90 resist=0.1;kaeya char lvl=90/90 cons=0 talent=6,6,6;kaeya add weapon="dullblade" refine=1 lvl=90/90;active kaeya;kaeya burst;`})
	if err == nil {
		t.Fatal("mixed gcsim executable statements were silently ignored")
	}
}

func TestNativeFlowMeasuresRootCompletionWithoutAUserSuppliedRoundDuration(t *testing.T) {
	request := engine.Request{SchemaVersion: "1", EngineRevision: engine.Revision, Seeds: []int64{29}, AutoRounds: true,
		Config:     `options duration=4;target lvl=90 resist=0.1;kaeya char lvl=90/90 cons=0 talent=6,6,6;kaeya add weapon="dullblade" refine=1 lvl=90/90;active kaeya;`,
		NativeFlow: &nativeflow.Program{SchemaVersion: "native-flow-v1", Source: "凯亚 e,wait(0.5)", Root: []nativeflow.Node{{ID: "e", Kind: "skill", Character: "kaeya"}, {ID: "w", Kind: "wait", Character: "kaeya", Seconds: .5}}}}
	report, err := engine.Evaluate(request)
	if err != nil {
		t.Fatal(err)
	}
	if !report.RoundMetricsAvailable || len(report.RoundTraces) != 1 || len(report.RoundTraces[0].Rounds) != 1 || !report.RoundTraces[0].Rounds[0].Complete {
		t.Fatalf("missing measured complete round: %+v", report.RoundTraces)
	}
	if report.RoundTraces[0].Rounds[0].DurationSeconds >= 4 {
		t.Fatal("round duration was replaced with the scene horizon")
	}
}

func TestWaterFlowRunsItsPreservedBranchesAndStandardChargeOnRealGcsim(t *testing.T) {
	var program nativeflow.Program
	if err := json.Unmarshal(nativeWater, &program); err != nil {
		t.Fatal(err)
	}
	config := `options duration=65;target lvl=100 resist=0.1 radius=2 pos=0,2.4;
zhongli char lvl=90/90 cons=0 talent=6,6,6;zhongli add weapon="blacktassel" refine=5 lvl=90/90;
furina char lvl=90/90 cons=0 talent=6,6,6;furina add weapon="fleuvecendreferryman" refine=5 lvl=90/90;
neuvillette char lvl=90/90 cons=0 talent=6,6,6;neuvillette add weapon="prototypeamber" refine=5 lvl=90/90;
jean char lvl=90/90 cons=0 talent=6,6,6;jean add weapon="favoniussword" refine=5 lvl=90/90;
active zhongli;`
	report, err := engine.Evaluate(engine.Request{SchemaVersion: "1", EngineRevision: engine.Revision, Seeds: []int64{17}, Config: config, NativeFlow: &program})
	if err != nil {
		t.Fatal(err)
	}
	if report.MeanDPS <= 0 || report.Support != "trial" {
		t.Fatalf("invalid trial: %+v", report)
	}
	charge, branch := false, false
	for _, trace := range report.NativeFlowTraces {
		for _, e := range trace.Events {
			if e.Kind == "action" && e.Detail == "charge" {
				charge = true
			}
			if e.Kind == "branch" {
				branch = true
			}
		}
	}
	if !charge || !branch {
		t.Fatalf("water macro/control flow not executed: %+v", report.NativeFlowTraces)
	}
}

func TestNativeFlowDrivesRealGcsimAndIsAlwaysAnExplicitTrial(t *testing.T) {
	raw := `{"schemaVersion":"1","engineRevision":"` + engine.Revision + `","seeds":[17],
      "config":"options duration=3;target lvl=90 resist=0.1;kaeya char lvl=90/90 cons=0 talent=6,6,6;kaeya add weapon=\"dullblade\" refine=1 lvl=90/90;active kaeya;",
      "nativeFlow":{"schemaVersion":"native-flow-v1","source":"凯亚 e,wait(2)","loop":false,
        "root":[{"id":"n1","kind":"skill","character":"kaeya","line":1},
                {"id":"n2","kind":"wait","character":"kaeya","seconds":2,"line":1}],"blocks":{},"timings":{}}}`
	var request engine.Request
	if err := json.Unmarshal([]byte(raw), &request); err != nil {
		t.Fatal(err)
	}
	report, err := engine.Evaluate(request)
	if err != nil {
		t.Fatal(err)
	}
	if report.MeanDPS <= 0 || report.Support != "trial" {
		t.Fatalf("native flow was ignored or misrepresented: dps=%v support=%v", report.MeanDPS, report.Support)
	}
}

func TestNativeFlowUnknownBranchSelectsOnlyItsDeclaredFallback(t *testing.T) {
	raw := `{"schemaVersion":"1","engineRevision":"` + engine.Revision + `","seeds":[23],
    "config":"options duration=3;target lvl=90 resist=0.1;kaeya char lvl=90/90 cons=0 talent=6,6,6;kaeya add weapon=\"dullblade\" refine=1 lvl=90/90;active kaeya;",
    "nativeFlow":{"schemaVersion":"native-flow-v1","source":"branch(if=low-hp(凯亚),then=甲,else=乙,unknown=丙)","root":[{"id":"branch","kind":"branch","line":1,"options":{"then":"甲","else":"乙","unknown":"丙"},"condition":{"op":"call","name":"low-hp","argument":"kaeya"}}],
    "blocks":{"甲":{"declaration":{"id":"a","kind":"segment"},"nodes":[{"id":"a1","kind":"burst","character":"kaeya"}]},
    "乙":{"declaration":{"id":"b","kind":"segment"},"nodes":[{"id":"b1","kind":"wait","character":"kaeya","seconds":1}]},
    "丙":{"declaration":{"id":"c","kind":"segment"},"nodes":[{"id":"c1","kind":"skill","character":"kaeya"}]}},"timings":{}}}`
	var request engine.Request
	if err := json.Unmarshal([]byte(raw), &request); err != nil {
		t.Fatal(err)
	}
	report, err := engine.Evaluate(request)
	if err != nil {
		t.Fatal(err)
	}
	encoded, _ := json.Marshal(report)
	var result map[string]any
	_ = json.Unmarshal(encoded, &result)
	traces, ok := result["nativeFlowTraces"].([]any)
	if !ok || len(traces) != 1 {
		t.Fatalf("missing native branch evidence: %s", encoded)
	}
	seen := false
	for _, event := range traces[0].(map[string]any)["events"].([]any) {
		value := event.(map[string]any)
		if value["kind"] == "branch" {
			seen = true
			if value["detail"] != "unknown:丙" {
				t.Fatalf("wrong branch: %v", value)
			}
		}
		if value["node"] == "a1" || value["node"] == "b1" {
			t.Fatalf("unselected branch executed: %v", value)
		}
	}
	if !seen || report.MeanDPS <= 0 {
		t.Fatal("fallback did not execute the real skill")
	}
}
